apiVersion: v1
appVersion: "1.31.0/1.32.0/1.33.0"
description: A Helm chart for OSC CCM cloud provider
name: osc-cloud-controller-manager
version: 0.7.0
kubeVersion: ">=1.30.0-0"
home: https://github.com/outscale/cloud-provider-osc/
sources:
  - https://github.com/outscale/cloud-provider-osc/
keywords:
  - osc
  - ows
  - CCM
  - LBU
maintainers:
  - name: 3DS Outscale
    email: support@outscale.com

